#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page

# Ensure Nginx is installed
apt-get update
apt-get install -y nginx

# Add the redirection configuration
sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx without systemctl
service nginx restart
