#!/usr/bin/env bash
# This script configures Nginx to serve a custom 404 page

# Ensure Nginx is installed
apt-get update
apt-get install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sed -i '/server_name _;/a \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx without systemctl
service nginx restart
