#!/usr/bin/env bash
# This script configures a new Ubuntu machine with Nginx and adds a custom HTTP response header

# Update package lists and install Nginx
apt-get -y update
apt-get -y install nginx

# Get the hostname of the server
HOST_NAME=$(hostname)

# Create a default index.html page
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify Nginx default site configuration
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $HOST_NAME;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOL

# Restart Nginx to apply changes
service nginx restart
