#!/usr/bin/env bash
# Configures a new HAproxy as a load balancer

# Update package index
apt-get -y update

# Install HAproxy (specific version 2.4.7 in this case)
apt-get -y install haproxy=2.4.7

# Configure HAproxy configuration file to distribute requests using a roundrobin algorithm
cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend sammykingx.tech
    bind 0:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 480640-web-01 100.26.56.243:80
    server 480640-web-02 3.85.168.149:80
EOF

# Restart HAproxy service
systemctl restart haproxy
