#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.4.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 480640-web-01 100.26.56.243:80
        server 480640-web-02 3.85.168.149:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
