#!/usr/bin/env bash

# Update the package list and install the specified version of HAproxy
apt-get update -y
apt-get install -y haproxy=2.4.*

# Backup the original HAproxy configuration file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Overwrite the HAproxy configuration file with the corrected configuration
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend sammykingx.tech
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 480640-web-01 100.26.56.243:80 check
    server 480640-web-02 3.85.168.149:80 check
EOL

# Validate HAproxy configuration
if haproxy -c -f /etc/haproxy/haproxy.cfg; then
    echo "HAproxy configuration is valid. Restarting service..."
    service haproxy restart
else
    echo "HAproxy configuration is invalid. Please check the configuration file."
    exit 1
fi

# Check the status of the HAproxy service
if systemctl is-active --quiet haproxy.service; then
    echo "HAproxy service started successfully."
else
    echo "Failed to start HAproxy service. See logs for details."
    journalctl -xe | tail -n 20
    exit 1
fi
